/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    CertificateTemplate: typeof import('./components/CertificateTemplate.vue')['default']
    ConfirmDialog: typeof import('./components/shared/ConfirmDialog.vue')['default']
    EmptyState: typeof import('./components/shared/EmptyState.vue')['default']
    ErrorDisplay: typeof import('./components/shared/ErrorDisplay.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NavigationDrawer: typeof import('./components/layout/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SF10Template: typeof import('./components/documents/SF10Template.vue')['default']
    SF9Template: typeof import('./components/documents/SF9Template.vue')['default']
    UnsavedChangesDialog: typeof import('./components/shared/UnsavedChangesDialog.vue')['default']
  }
}
