/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/audit-logs': RouteRecordInfo<'/admin/audit-logs', '/admin/audit-logs', Record<never, never>, Record<never, never>>,
    '/admin/classes': RouteRecordInfo<'/admin/classes', '/admin/classes', Record<never, never>, Record<never, never>>,
    '/admin/school-years': RouteRecordInfo<'/admin/school-years', '/admin/school-years', Record<never, never>, Record<never, never>>,
    '/admin/settings': RouteRecordInfo<'/admin/settings', '/admin/settings', Record<never, never>, Record<never, never>>,
    '/admin/subjects': RouteRecordInfo<'/admin/subjects', '/admin/subjects', Record<never, never>, Record<never, never>>,
    '/admin/teachers': RouteRecordInfo<'/admin/teachers', '/admin/teachers', Record<never, never>, Record<never, never>>,
    '/admin/unlock-requests': RouteRecordInfo<'/admin/unlock-requests', '/admin/unlock-requests', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/student/': RouteRecordInfo<'/student/', '/student', Record<never, never>, Record<never, never>>,
    '/student/certificates': RouteRecordInfo<'/student/certificates', '/student/certificates', Record<never, never>, Record<never, never>>,
    '/student/documents': RouteRecordInfo<'/student/documents', '/student/documents', Record<never, never>, Record<never, never>>,
    '/student/grades': RouteRecordInfo<'/student/grades', '/student/grades', Record<never, never>, Record<never, never>>,
    '/teacher/': RouteRecordInfo<'/teacher/', '/teacher', Record<never, never>, Record<never, never>>,
    '/teacher/activity': RouteRecordInfo<'/teacher/activity', '/teacher/activity', Record<never, never>, Record<never, never>>,
    '/teacher/certificates/': RouteRecordInfo<'/teacher/certificates/', '/teacher/certificates', Record<never, never>, Record<never, never>>,
    '/teacher/certificates/[studentId]/[schoolYearId]': RouteRecordInfo<'/teacher/certificates/[studentId]/[schoolYearId]', '/teacher/certificates/:studentId/:schoolYearId', { studentId: ParamValue<true>, schoolYearId: ParamValue<true> }, { studentId: ParamValue<false>, schoolYearId: ParamValue<false> }>,
    '/teacher/classes': RouteRecordInfo<'/teacher/classes', '/teacher/classes', Record<never, never>, Record<never, never>, '/teacher/classes/[id]' | '/teacher/classes/[id]/grades'>,
    '/teacher/classes/[id]': RouteRecordInfo<'/teacher/classes/[id]', '/teacher/classes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }, '/teacher/classes/[id]/grades'>,
    '/teacher/classes/[id]/grades': RouteRecordInfo<'/teacher/classes/[id]/grades', '/teacher/classes/:id/grades', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/teacher/documents/': RouteRecordInfo<'/teacher/documents/', '/teacher/documents', Record<never, never>, Record<never, never>>,
    '/teacher/documents/sf10/[studentId]': RouteRecordInfo<'/teacher/documents/sf10/[studentId]', '/teacher/documents/sf10/:studentId', { studentId: ParamValue<true> }, { studentId: ParamValue<false> }>,
    '/teacher/documents/sf9/[studentId]/[schoolYearId]': RouteRecordInfo<'/teacher/documents/sf9/[studentId]/[schoolYearId]', '/teacher/documents/sf9/:studentId/:schoolYearId', { studentId: ParamValue<true>, schoolYearId: ParamValue<true> }, { studentId: ParamValue<false>, schoolYearId: ParamValue<false> }>,
    '/teacher/grades': RouteRecordInfo<'/teacher/grades', '/teacher/grades', Record<never, never>, Record<never, never>>,
    '/test-supabase': RouteRecordInfo<'/test-supabase', '/test-supabase', Record<never, never>, Record<never, never>>,
    '/verify': RouteRecordInfo<'/verify', '/verify', Record<never, never>, Record<never, never>, '/verify/[id]'>,
    '/verify/[id]': RouteRecordInfo<'/verify/[id]', '/verify/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/admin/audit-logs.vue': {
      routes: '/admin/audit-logs'
      views: never
    }
    'src/pages/admin/classes.vue': {
      routes: '/admin/classes'
      views: never
    }
    'src/pages/admin/school-years.vue': {
      routes: '/admin/school-years'
      views: never
    }
    'src/pages/admin/settings.vue': {
      routes: '/admin/settings'
      views: never
    }
    'src/pages/admin/subjects.vue': {
      routes: '/admin/subjects'
      views: never
    }
    'src/pages/admin/teachers.vue': {
      routes: '/admin/teachers'
      views: never
    }
    'src/pages/admin/unlock-requests.vue': {
      routes: '/admin/unlock-requests'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/student/index.vue': {
      routes: '/student/'
      views: never
    }
    'src/pages/student/certificates.vue': {
      routes: '/student/certificates'
      views: never
    }
    'src/pages/student/documents.vue': {
      routes: '/student/documents'
      views: never
    }
    'src/pages/student/grades.vue': {
      routes: '/student/grades'
      views: never
    }
    'src/pages/teacher/index.vue': {
      routes: '/teacher/'
      views: never
    }
    'src/pages/teacher/activity.vue': {
      routes: '/teacher/activity'
      views: never
    }
    'src/pages/teacher/certificates/index.vue': {
      routes: '/teacher/certificates/'
      views: never
    }
    'src/pages/teacher/certificates/[studentId]/[schoolYearId].vue': {
      routes: '/teacher/certificates/[studentId]/[schoolYearId]'
      views: never
    }
    'src/pages/teacher/classes.vue': {
      routes: '/teacher/classes' | '/teacher/classes/[id]' | '/teacher/classes/[id]/grades'
      views: 'default'
    }
    'src/pages/teacher/classes/[id].vue': {
      routes: '/teacher/classes/[id]' | '/teacher/classes/[id]/grades'
      views: 'default'
    }
    'src/pages/teacher/classes/[id]/grades.vue': {
      routes: '/teacher/classes/[id]/grades'
      views: never
    }
    'src/pages/teacher/documents/index.vue': {
      routes: '/teacher/documents/'
      views: never
    }
    'src/pages/teacher/documents/sf10/[studentId].vue': {
      routes: '/teacher/documents/sf10/[studentId]'
      views: never
    }
    'src/pages/teacher/documents/sf9/[studentId]/[schoolYearId].vue': {
      routes: '/teacher/documents/sf9/[studentId]/[schoolYearId]'
      views: never
    }
    'src/pages/teacher/grades.vue': {
      routes: '/teacher/grades'
      views: never
    }
    'src/pages/test-supabase.vue': {
      routes: '/test-supabase'
      views: never
    }
    'src/pages/verify.vue': {
      routes: '/verify' | '/verify/[id]'
      views: 'default'
    }
    'src/pages/verify/[id].vue': {
      routes: '/verify/[id]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
